### ISSUE TITLE
Runtime Error 500

### ISSUE THREAD

**Issue by jeffeastman** [DBCG/cqf-ruler#2]
I updated and rebuilt the project today and loaded the bundle at cqf-ruler/src/main/resources/database-init-bundle.json. Running the following query from the documentation still yields the following errors.

```
Sending 'GET' request to URL: http://localhost:8080/cqf-ruler/baseDstu3/Measure/col/$evaluate?patient=Patient-12214&startPeriod=2014-01&endPeriod=2014-12
Error 500

```
```
2017-07-17 10:15:23.069 [http-nio-8080-exec-6] INFO  ca.uhn.fhir.context.FhirContext [FhirContext.java:172] Creating new FHIR context for FHIR version [DSTU3]
2017-07-17 10:15:23.084 [http-nio-8080-exec-6] INFO  c.u.f.j.dao.BaseHapiFhirResourceDao [BaseHapiFhirResourceDao.java:788] Processed read on Measure/col in 62ms
2017-07-17 10:15:23.087 [http-nio-8080-exec-6] INFO  c.u.f.j.dao.BaseHapiFhirResourceDao [BaseHapiFhirResourceDao.java:788] Processed read on Library/col-logic in 2ms
2017-07-17 10:15:23.606 [http-nio-8080-exec-6] INFO  c.u.f.j.dao.BaseHapiFhirResourceDao [BaseHapiFhirResourceDao.java:788] Processed read on Patient-12214 in 2ms
2017-07-17 10:15:23.702 [http-nio-8080-exec-6] INFO  c.u.f.j.s.SearchCoordinatorSvcImpl [SearchCoordinatorSvcImpl.java:342] Search initial phase completed in 13ms
2017-07-17 10:15:23.703 [http-nio-8080-exec-6] INFO  c.u.f.j.s.SearchCoordinatorSvcImpl [SearchCoordinatorSvcImpl.java:567] Requesting search PIDs from 0-50
2017-07-17 10:15:23.762 [search_coord_1] INFO  ca.uhn.fhir.jpa.dao.SearchBuilder [SearchBuilder.java:2025] Initial query result returned in 21ms for query 4a42b02a-5d13-4188-9e13-77ed8388b0d1
2017-07-17 10:15:23.763 [search_coord_1] INFO  ca.uhn.fhir.jpa.dao.SearchBuilder [SearchBuilder.java:2029] Query found 1 matches in 22ms for query 4a42b02a-5d13-4188-9e13-77ed8388b0d1
2017-07-17 10:15:23.791 [search_coord_1] INFO  c.u.f.j.s.SearchCoordinatorSvcImpl [SearchCoordinatorSvcImpl.java:484] Completed search for 1 resources in 89ms
2017-07-17 10:15:24.235 [http-nio-8080-exec-6] ERROR c.u.f.r.s.i.ExceptionHandlingInterceptor [ExceptionHandlingInterceptor.java:128] Failure during REST processing
ca.uhn.fhir.rest.server.exceptions.InternalErrorException: Failed to call access method
	at ca.uhn.fhir.rest.method.BaseMethodBinding.invokeServerMethod(BaseMethodBinding.java:263)
	at ca.uhn.fhir.rest.method.OperationMethodBinding.invokeServer(OperationMethodBinding.java:300)
	at ca.uhn.fhir.rest.method.BaseResourceReturningMethodBinding.doInvokeServer(BaseResourceReturningMethodBinding.java:306)
	at ca.uhn.fhir.rest.method.BaseResourceReturningMethodBinding.invokeServer(BaseResourceReturningMethodBinding.java:258)
	at ca.uhn.fhir.rest.method.OperationMethodBinding.invokeServer(OperationMethodBinding.java:275)
	at ca.uhn.fhir.rest.server.RestfulServer.handleRequest(RestfulServer.java:643)
	at ca.uhn.fhir.rest.server.RestfulServer.doGet(RestfulServer.java:1193)
	at ca.uhn.fhir.rest.server.RestfulServer.service(RestfulServer.java:1169)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.ebaysf.web.cors.CORSFilter.handleNonCORS(CORSFilter.java:437)
	at org.ebaysf.web.cors.CORSFilter.doFilter(CORSFilter.java:172)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:212)

```

**Comment by c-schuler** [comment]
Hi there Jeff.

The error you're seeing is caused by a bug (I think) in Hapi version 2.5. There seems to be an issue when a query string includes more than 5 code tokens. I have rolled the Ruler back to use Hapi 2.4 and have verified that all operations are functioning properly.

Sorry for the inconvenience! =)

**Comment by jeffeastman** [comment]
Agreed, its working now. Thanks,

Jeff
