### ISSUE TITLE
ClassCastException in develop branch

### ISSUE THREAD

**Issue by drdavec** [DBCG/cqf-ruler#246]
I am preparing a test case for the connectathon next week and switched to the 'develop' branch for testing (is this the version planned for connecathon test server?).  I get a runtime exception that I did not see on master.  I am using PlanDefinition to create CDSHook patient-view services.

java.lang.ClassCastException: class org.opencds.cqf.cql.engine.runtime.Code cannot be cast to class org.hl7.fhir.instance.model.api.IBase (org.opencds.cqf.cql.engine.runtime.Code and org.hl7.fhir.instance.model.api.IBase are in unnamed module of loader org.eclipse.jetty.webapp.WebAppClassLoader @d383a77)
        at org.opencds.cqf.cql.evaluator.execution.util.CodeUtil.tryIterableThenConcept(CodeUtil.java:26)
        at org.opencds.cqf.cql.evaluator.execution.util.CodeUtil.getElmCodesFromObject(CodeUtil.java:19)
        at org.opencds.cqf.cds.providers.PrefetchDataProviderHelper.checkCodeMembership(PrefetchDataProviderHelper.java:195)
        at org.opencds.cqf.cds.providers.PrefetchDataProviderR4.retrieve(PrefetchDataProviderR4.java:117)
        at org.opencds.cqf.cds.providers.PriorityRetrieveProvider.retrieve(PriorityRetrieveProvider.java:30)
        at org.opencds.cqf.cql.engine.data.CompositeDataProvider.retrieve(CompositeDataProvider.java:83)
        at org.opencds.cqf.cql.engine.elm.execution.RetrieveEvaluator.internalEvaluate(RetrieveEvaluator.java:59)
        at org.opencds.cqf.cql.engine.elm.execution.Executable.evaluate(Executable.java:17)
        at org.opencds.cqf.cql.engine.elm.execution.FunctionRefEvaluator.internalEvaluate(FunctionRefEvaluator.java:17)
        at org.opencds.cqf.cql.engine.elm.execution.Executable.evaluate(Executable.java:17)
        at org.opencds.cqf.cql.engine.elm.execution.FunctionRefEvaluator.internalEvaluate(FunctionRefEvaluator.java:17)
        at org.opencds.cqf.cql.engine.elm.execution.Executable.evaluate(Executable.java:17)
        at org.opencds.cqf.cql.engine.elm.execution.ExpressionDefEvaluator.internalEvaluate(ExpressionDefEvaluator.java:17)
        at org.opencds.cqf.cql.engine.elm.execution.Executable.evaluate(Executable.java:17)
        at org.opencds.cqf.cql.engine.elm.execution.ExpressionRefEvaluator.internalEvaluate(ExpressionRefEvaluator.java:11)
        at org.opencds.cqf.cql.engine.elm.execution.Executable.evaluate(Executable.java:17)
        at org.opencds.cqf.cql.engine.elm.execution.ExistsEvaluator.internalEvaluate(ExistsEvaluator.java:28)
        at org.opencds.cqf.cql.engine.elm.execution.Executable.evaluate(Executable.java:17)
        at org.opencds.cqf.cds.hooks.R4HookEvaluator.resolveActions(R4HookEvaluator.java:69)
        at org.opencds.cqf.cds.hooks.R4HookEvaluator.evaluateCdsHooksPlanDefinition(R4HookEvaluator.java:47)
        at org.opencds.cqf.cds.hooks.R4HookEvaluator.evaluateCdsHooksPlanDefinition(R4HookEvaluator.java:17)

**Comment by JPercival** [comment]
@drdavec Apologies for the delay. I know the connectathon starts today. Do you happen to have a repro? I will look at it.

**Comment by drdavec** [comment]
Thanks JP, here is the message I sent to Bryn with link to repo with
resources and CQL.

I am preparing an example for the Care Management connectathon track,
following CPG IG for a small hypertension example using CDS Hooks
recommendation with ECA rules.  Partially working using cqf-ruler on
localhost, with master branch.  I get info cards, but cannot get a
suggestion card with embedded MedicationRequest.  Trying to run on the
'develop' branch and get a ClassCastException with the same definition
resources.  Also same error on your open sandbox.  Hoping you can spot a
simple error in CQL, or a quick fix to cqf-ruler in develop branch.

The content is here:
https://github.com/chronic-care/cds-logic/tree/master/htn-management

I loaded these resources into the cqm-sandbox and get the expected
cds-services response.  But trying to invoke the htn-management hook
results in ClassCastException copied below.

https://cqm-sandbox.alphora.com/cqf-ruler-r4/cds-services

ERROR: Exception in CQL Execution. Unexpected exception caught during
execution: java.lang.ClassCastException: class
org.opencds.cqf.cql.engine.runtime.Code cannot be cast to class
org.hl7.fhir.instance.model.api.IBase
(org.opencds.cqf.cql.engine.runtime.Code and
org.hl7.fhir.instance.model.api.IBase are in unnamed module of loader
org.eclipse.jetty.webapp.WebAppClassLoader @47e2e487)
org.opencds.cqf.cql.engine.exception.CqlException: Unexpected exception
caught during execution: java.lang.ClassCastException: class
org.opencds.cqf.cql.engine.runtime.Code cannot be cast to class
org.hl7.fhir.instance.model.api.IBase
(org.opencds.cqf.cql.engine.runtime.Code and
org.hl7.fhir.instance.model.api.IBase are in unnamed module of loader
org.eclipse.jetty.webapp.WebAppClassLoader @47e2e487) at
org.opencds.cqf.cql.engine.elm.execution.Executable.evaluate(Executable.java:36)
at
org.opencds.cqf.cql.engine.elm.execution.QueryEvaluator.internalEvaluate(QueryEvaluator.java:162)
at
org.opencds.cqf.cql.engine.elm.execution.Executable.evaluate(Executable.java:17)
at
org.opencds.cqf.cql.engine.elm.execution.ExpressionDefEvaluator.internalEvaluate(ExpressionDefEvaluator.java:17)
at
org.opencds.cqf.cql.engine.elm.execution.Executable.evaluate(Executable.java:17)
at
org.opencds.cqf.cql.engine.elm.execution.ExpressionRefEvaluator.internalEvaluate(ExpressionRefEvaluator.java:11)
at
org.opencds.cqf.cql.engine.elm.execution.Executable.evaluate(Executable.java:17)
at
org.opencds.cqf.cql.engine.elm.execution.QueryEvaluator.internalEvaluate(QueryEvaluator.java:162)
at
org.opencds.cqf.cql.engine.elm.execution.Executable.evaluate(Executable.java:17)
at
org.opencds.cqf.cql.engine.elm.execution.LastEvaluator.internalEvaluate(LastEvaluator.java:30)
at
org.opencds.cqf.cql.engine.elm.execution.Executable.evaluate(Executable.java:17)
at
org.opencds.cqf.cql.engine.elm.execution.ExpressionDefEvaluator.internalEvaluate(ExpressionDefEvaluator.java:17)
at
org.opencds.cqf.cql.engine.elm.execution.Executable.evaluate(Executable.java:17)
at
org.opencds.cqf.cql.engine.elm.execution.ExpressionRefEvaluator.internalEvaluate(ExpressionRefEvaluator.java:11)
at
org.opencds.cqf.cql.engine.elm.execution.Executable.evaluate(Executable.java:17)
at
org.opencds.cqf.cql.engine.elm.execution.PropertyEvaluator.internalEvaluate(PropertyEvaluator.java:13)
at
org.opencds.cqf.cql.engine.elm.execution.Executable.evaluate(Executable.java:17)
at
org.opencds.cqf.cql.engine.elm.execution.FunctionRefEvaluator.internalEvaluate(FunctionRefEvaluator.java:17)
at
org.opencds.cqf.cql.engine.elm.execution.Executable.evaluate(Executable.java:17)
at
org.opencds.cqf.cql.engine.elm.execution.GreaterEvaluator.internalEvaluate(GreaterEvaluator.java:97)
at
org.opencds.cqf.cql.engine.elm.execution.Executable.evaluate(Executable.java:17)
at

**Comment by JPercival** [comment]
Resolved with latest cql-evaluator SNAPSHOT, which is used in cqf-ruler/develop
