### ISSUE TITLE
DSF Measure Failure

### ISSUE THREAD

**Issue by jeffeastman** [DBCG/cqf-ruler#25]
I'm getting this result for all patients evaluating the DSF measure against (I think) all the latest bits:

```
2017-12-20 12:05:19.076 [http-nio-8080-exec-4] ERROR c.u.f.r.s.i.ExceptionHandlingInterceptor [ExceptionHandlingInterceptor.java:129] Failure during REST processing
ca.uhn.fhir.rest.server.exceptions.InternalErrorException: Failed to call access method
	at ca.uhn.fhir.rest.server.method.BaseMethodBinding.invokeServerMethod(BaseMethodBinding.java:253)
	at ca.uhn.fhir.rest.server.method.OperationMethodBinding.invokeServer(OperationMethodBinding.java:254)
	at ca.uhn.fhir.rest.server.method.BaseResourceReturningMethodBinding.doInvokeServer(BaseResourceReturningMethodBinding.java:157)
	at ca.uhn.fhir.rest.server.method.BaseResourceReturningMethodBinding.invokeServer(BaseResourceReturningMethodBinding.java:136)
	at ca.uhn.fhir.rest.server.method.OperationMethodBinding.invokeServer(OperationMethodBinding.java:229)
	at ca.uhn.fhir.rest.server.RestfulServer.handleRequest(RestfulServer.java:858)
	at ca.uhn.fhir.rest.server.RestfulServer.doGet(RestfulServer.java:1453)
	at ca.uhn.fhir.rest.server.RestfulServer.service(RestfulServer.java:1429)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.ebaysf.web.cors.CORSFilter.handleNonCORS(CORSFilter.java:437)
	at org.ebaysf.web.cors.CORSFilter.doFilter(CORSFilter.java:172)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:212)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:141)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:616)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:521)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1096)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:674)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1500)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1456)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.reflect.InvocationTargetException: null
	at sun.reflect.GeneratedMethodAccessor228.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at ca.uhn.fhir.rest.server.method.BaseMethodBinding.invokeServerMethod(BaseMethodBinding.java:248)
	... 32 common frames omitted
Caused by: ca.uhn.fhir.parser.DataFormatException: Invalid date/time format: "-value"
	at ca.uhn.fhir.model.primitive.BaseDateTimeDt.throwBadDateFormat(BaseDateTimeDt.java:650)
	at ca.uhn.fhir.model.primitive.BaseDateTimeDt.parseInt(BaseDateTimeDt.java:444)
	at ca.uhn.fhir.model.primitive.BaseDateTimeDt.parse(BaseDateTimeDt.java:347)
	at ca.uhn.fhir.model.primitive.BaseDateTimeDt.parse(BaseDateTimeDt.java:39)
	at ca.uhn.fhir.model.api.BasePrimitive.setValueAsString(BasePrimitive.java:111)
	at ca.uhn.fhir.model.primitive.BaseDateTimeDt.setValueAsString(BaseDateTimeDt.java:638)
	at ca.uhn.fhir.rest.param.DateParam.setValueAsString(DateParam.java:202)
	at ca.uhn.fhir.rest.param.DateParam.<init>(DateParam.java:89)
	at org.opencds.cqf.providers.JpaDataProvider.retrieve(JpaDataProvider.java:88)
	at org.opencds.cqf.cql.elm.execution.RetrieveEvaluator.evaluate(RetrieveEvaluator.java:52)
	at org.opencds.cqf.cql.elm.execution.QueryEvaluator.evaluate(QueryEvaluator.java:226)
	at org.opencds.cqf.cql.elm.execution.ExistsEvaluator.evaluate(ExistsEvaluator.java:32)
	at org.opencds.cqf.cql.elm.execution.AndEvaluator.evaluate(AndEvaluator.java:38)
	at org.opencds.cqf.cql.elm.execution.ExpressionDefEvaluator.evaluate(ExpressionDefEvaluator.java:20)
	at org.opencds.cqf.helpers.FhirMeasureEvaluator.resolveGroupings(FhirMeasureEvaluator.java:28)
	at org.opencds.cqf.helpers.FhirMeasureEvaluator.evaluate(FhirMeasureEvaluator.java:84)
	at org.opencds.cqf.helpers.FhirMeasureEvaluator.evaluate(FhirMeasureEvaluator.java:88)
	at org.opencds.cqf.providers.FHIRMeasureResourceProvider.evaluatePatientMeasure(FHIRMeasureResourceProvider.java:223)
	at org.opencds.cqf.providers.FHIRMeasureResourceProvider.evaluateMeasure(FHIRMeasureResourceProvider.java:195)
	... 36 common frames omitted
2017-12-20 12:05:19.076 [http-nio-8080-exec-4] INFO  logging.accesslog [LoggingInterceptor.java:155] ERROR - extended-operation-instance - Measure/measure-dsf

```

**Comment by jeffeastman** [comment]
This logic works just fine in my memory evaluator:

```
Measure = Measure/measure-dsf
	denominator = 363
	initial-population = 200
	numerator = 305

```

**Comment by jeffeastman** [comment]
The odd numerator and denominator counts are due to a defect in the FhirMeasureEvaluator that does not properly code the MeasureReportGroupComponents to handle multiple numerators, denominators, etc.  See #28

**Comment by jeffeastman** [comment]
This looks like a PatientGen coding error since DiagnosticReports are coded as Observations but with an effective Period rather than the dataTime that the CQL is expecting. So I will regenerate the test encounters and test this with the new encoding. It is likely that the fix to #27 will then allow this measure to succeed.

**Comment by jeffeastman** [comment]
Converging on the cause. This blows up in JpaDataProvider line

`			        low = new DateParam(ParamPrefixEnum.GREATERTHAN_OR_EQUALS, convertPathToSearchParam(dateLowPath != null ? dateLowPath : datePath));
`

because, I think, convertPathToSearchParam() is returning "effective-value" instead of the date. Digging into how this should work and why its not.

**Comment by jeffeastman** [comment]
DRR and DMS measures do not exercise this particular code, so the problem is DSF measure-specific. The failure is in a rather normal Numerator 1 CQL expression:

```
// Depression Screening
define "Numerator 1":
	"Initial Population"
	and
	exists (
		[Observation: "Depression Screen"] DepressionScreen
			where DepressionScreen.status.value in { 'final', 'amended' }
				and DepressionScreen.effective.value in "Measurement Period"
	)
```
that's compiled into:

```
               <operand localId="124" xsi:type="Query">
                  <source localId="110" alias="DepressionScreen">
                     <expression localId="109" dataType="fhir:Observation" codeProperty="code" dateProperty="effective.value" xsi:type="Retrieve">
                        <codes name="Depression Screen" xsi:type="ValueSetRef"/>
                        <dateRange localId="121" name="Measurement Period" xsi:type="ParameterRef"/>
                     </expression>
                  </source>
                  <where localId="117" xsi:type="In">
                     <operand localId="113" path="value" xsi:type="Property">
                        <source localId="112" path="status" scope="DepressionScreen" xsi:type="Property"/>
                     </operand>
                     <operand localId="116" xsi:type="List">
                        <element localId="114" valueType="t:String" value="final" xsi:type="Literal"/>
                        <element localId="115" valueType="t:String" value="amended" xsi:type="Literal"/>
                     </operand>
                  </where>
               </operand>
            </operand>

```

**Comment by jeffeastman** [comment]
Turns out, none of the other working measures exercise this code: BCS, CCS, COL and PVS don't either. @c-schuler , @brynrhodes any ideas while I'm floundering a bit here?

**Comment by brynrhodes** [comment]
I'd have to dig into see what's actually going wrong with the filter there, but a possible workaround is to turn off the dateRangeOptimization in the translator. That will at least apply that filter after the retrieve, rather than as part of it, which is where the problem is happening.

**Comment by c-schuler** [comment]
Pushed a [commit](https://github.com/DBCG/cqf-ruler/commit/283c430d482904da80dd434b375a0a380b0e655e). Get the latest and try again.

**Comment by jeffeastman** [comment]
Better, but now its throwing:

```
Caused by: ca.uhn.fhir.parser.DataFormatException: Lower bound comparator must be > or >=, can not be le
	at ca.uhn.fhir.rest.param.DateRangeParam.validateAndThrowDataFormatExceptionIfInvalid(DateRangeParam.java:469)
	at ca.uhn.fhir.rest.param.DateRangeParam.setRangeFromDatesInclusive(DateRangeParam.java:321)
	at ca.uhn.fhir.rest.param.DateRangeParam.<init>(DateRangeParam.java:120)
	at org.opencds.cqf.providers.JpaDataProvider.retrieve(JpaDataProvider.java:112)
	at org.opencds.cqf.cql.elm.execution.RetrieveEvaluator.evaluate(RetrieveEvaluator.java:52)

```
Looks like the GREATERTHAN_OR_EQUALS and LESSTHAN_OR_EQUALS are the wrong flavor.

also, if you could add the null check in

```
			if (valueSet != null && terminologyProvider != null && expandValueSets) {
				ValueSetInfo valueSetInfo = new ValueSetInfo().withId(valueSet);
				codes = terminologyProvider.expand(valueSetInfo);
			}

```

it will resolve the other two issues #26 & #27

**Comment by jeffeastman** [comment]
Could it be as simple as reversing low and high in this?

`				rangeParam = new DateRangeParam(high, low);
`

I'm going to test it.

**Comment by jeffeastman** [comment]
That got me a bit farther to the next layer of the onion. Adding a try around getResources:

```
		try {
			resourceList = bundleProvider.getResources(0, 50);
		} catch (Exception e) {
			e.printStackTrace();
			throw e;
		}

```

throws this:

```
ca.uhn.fhir.rest.server.exceptions.InvalidRequestException: Unknown search parameter effective-value for resource type Observation
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at ca.uhn.fhir.rest.server.exceptions.BaseServerResponseException.newInstance(BaseServerResponseException.java:301)
	at ca.uhn.fhir.jpa.search.SearchCoordinatorSvcImpl.verifySearchHasntFailedOrThrowInternalErrorException(SearchCoordinatorSvcImpl.java:419)
	at ca.uhn.fhir.jpa.search.PersistedJpaSearchFirstPageBundleProvider.getResources(PersistedJpaSearchFirstPageBundleProvider.java:56)
	at org.opencds.cqf.providers.JpaDataProvider.retrieve(JpaDataProvider.java:122)

```

**Comment by c-schuler** [comment]
There were a few issues. First, the CQL needed a small tweak to workaround a translation issue (Could not resolve code path medicationCodeableConcept for the type of the retrieve FHIR.MedicationDispense). So grab the newest [Library resource](https://github.com/cqframework/hedis-ig/blob/master/resources/library/library-dsf-logic.json). Second, the JpaDataProvider needed some work to resolve code and date paths correctly, including the reversal of low and high values like you stated above. I have tested these fixes with Patient-1138 to verify. Let me know if this is now operational for you.

**Comment by jeffeastman** [comment]
This measure is now working so closing the issue

```
http://localhost:8080/cqf-ruler/baseDstu3/Patient/Patient-1137/_history/1
http://localhost:8080/cqf-ruler/baseDstu3/Patient/Patient-6529/_history/1
	patient is in initial-population
	patient is in denominator
http://localhost:8080/cqf-ruler/baseDstu3/Patient/Patient-1132/_history/1
	patient is in initial-population
	patient is in numerator
	patient is in denominator
	patient is in denominator
http://localhost:8080/cqf-ruler/baseDstu3/Patient/Patient-6481/_history/1
	patient is in initial-population
	patient is in numerator
	patient is in denominator
	patient is in denominator

```
