### ISSUE TITLE
Cannot build the package because of failed test cases

### ISSUE THREAD

**Issue by kugoo109** [DBCG/cqf-ruler#43]
Please double check again. I cannot build the package because of failed test cases. 

Below is the surefire report for the test cases:
```
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.005 s - in org.opencds.cqf.RulerHelperTests
[INFO]
[INFO] Results:
[INFO]
[ERROR] Errors:
[ERROR]   TestBase.runHedisCdsTests:76 » UnprocessableEntity HTTP 422 Unprocessable Enti...
[ERROR]   TestBase.runMeasureEvaluationTests:27 » UnprocessableEntity HTTP 422 Unprocess...
[INFO]
[ERROR] Tests run: 9, Failures: 0, Errors: 2, Skipped: 0
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:23 min
[INFO] Finished at: 2018-05-10T22:30:08+02:00
[INFO] ------------------------------------------------------------------------

-------------------------------------------------------------------------------
Test set: org.opencds.cqf.TestBase
-------------------------------------------------------------------------------
Tests run: 4, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 62.823 s <<< FAILURE! - in org.opencds.cqf.TestBase
runHedisCdsTests(org.opencds.cqf.TestBase)  Time elapsed: 0.171 s  <<< ERROR!
ca.uhn.fhir.rest.server.exceptions.UnprocessableEntityException: HTTP 422 Unprocessable Entity: Can not create multiple code systems with URI "https://www.cms.gov/Medicare/CMS-Forms/CMS-Forms/CMS-Forms-Items/CMS1196256.html/fl42", already have one with resource ID: CodeSystem/2.16.840.1.113883.3.88.12.3221.8.11
	at org.opencds.cqf.TestBase.runHedisCdsTests(TestBase.java:76)

runMeasureEvaluationTests(org.opencds.cqf.TestBase)  Time elapsed: 3.407 s  <<< ERROR!
ca.uhn.fhir.rest.server.exceptions.UnprocessableEntityException: HTTP 422 Unprocessable Entity: Can not create multiple code systems with URI "https://www.cms.gov/Medicare/CMS-Forms/CMS-Forms/CMS-Forms-Items/CMS1196256.html/fl42", already have one with resource ID: CodeSystem/2.16.840.1.113883.3.88.12.3221.8.11
	at org.opencds.cqf.TestBase.runMeasureEvaluationTests(TestBase.java:27)
```

**Comment by c-schuler** [comment]
Try deleting the target directory and rebuilding.

**Comment by c-schuler** [comment]
Note that deleting the target directory will reset the database. If you don't want to do that, delete the codesystem with the https://www.cms.gov/Medicare/CMS-Forms/CMS-Forms/CMS-Forms-Items/CMS1196256.html/fl42 URI.

**Comment by kugoo109** [comment]
Thx, it built successfully at the latest commit [9f23520](https://github.com/DBCG/cqf-ruler/commit/9f23520b3d93fd451d4f7fb96ac4140d1e5923c6)
