### ISSUE TITLE
Does Ruler Return Correct evaluatedResourceBundle?

### ISSUE THREAD

**Issue by jeffeastman** [DBCG/cqf-ruler#57]
This query gets back a bundle from the MiHIN Connectathon Quality Server but it can't seem to return the evaluated resource bundle. So I wonder if this is working or is it my test code (again)?

```
Sending 'GET' request to URL: https://fire-pit.mihin.org/cqf-ruler/baseDstu3/Measure/measure-bcs/$evaluate-measure?patient=Patient-1137&periodStart=2016-1&periodEnd=2018-12&reportType=patient

Sending 'GET' request to URL: https://fire-pit.mihin.org/cqf-ruler/baseDstu3/#8d416c27-7a7b-4621-9d9f-eefcadc5e73e?_raw=true
e400 null
java.lang.RuntimeException: FHIR Read error 400
	at org.mihin.patientgen.fhir.FhirServer.read(FhirServer.java:129)
	at org.mihin.patientgen.cql.MiHINConnectathonTests.convertReport(MiHINConnectathonTests.java:293)
	at org.mihin.patientgen.cql.MiHINConnectathonTests.testConvertMeasureReport(MiHINConnectathonTests.java:282)

```

**Comment by c-schuler** [comment]
The Bundle is returned as a contained resource in the MeasureReport response, which is why the id reference has the "#" prefix. It isn't saved in the Ruler (if it was, your GET request still wouldn't work as you aren't specifying that you're looking for a Bundle). You will also need to get the latest as there was a bug fix for populating the evaluated resources bundle.

**Comment by jeffeastman** [comment]
Thanks, I figured there was some pilot error. Rebuilding so I can look for the contained resource instead. I wondered about the # and lack of resourceType.

**Comment by jeffeastman** [comment]
Ok, I've repopulated my local server. When I run this on the public connectathon server, I get:
```
Sending 'GET' request to URL: https://fire-pit.mihin.org/cqf-ruler/baseDstu3/Measure/measure-bcs/$evaluate-measure?patient=Patient-6535&periodStart=2016-1&periodEnd=2018-12&reportType=patient

Barbara April Howe [63]  (Patient-6535) is in initial-population
	and also in numerator
	and also in denominator
```
but when I run it on the latest ruler bits, I get an e400:
```
Sending 'GET' request to URL: http://localhost:8080/cqf-ruler/baseDstu3/Measure/measure-bcs/$evaluate-measure?patient=Patient-6535&periodStart=2016-1&periodEnd=2018-12&reportType=patient
e400 Barbara April Howe http://localhost:8080/cqf-ruler/baseDstu3/Patient/Patient-6535/_history/1
```

**Comment by c-schuler** [comment]
Huh... Works for me. I don't have all the history data loaded, but I do have all the patients locally. I have no idea why that would throw a 400.

**Comment by jeffeastman** [comment]
Server log is showing this warning. Don't know what has changed since connectathon bits.

```
2018-06-13 08:59:28.001 [search_coord_9] WARN  c.u.f.j.s.SearchCoordinatorSvcImpl [SearchCoordinatorSvcImpl.java:537] Failed during search due to invalid request: ca.uhn.fhir.rest.server.exceptions.InvalidRequestException: Unknown code system: http://fhir.ext.apelon.com/dtsserverws/fhir/ValueSet/2.16.840.1.113883.3.464.1004.1168.8
2018-06-13 08:59:28.001 [http-nio-8080-exec-8] INFO  c.u.f.j.s.SearchCoordinatorSvcImpl [SearchCoordinatorSvcImpl.java:647] Proceeding, as we have 0 results
2018-06-13 08:59:28.001 [http-nio-8080-exec-8] WARN  c.u.f.r.s.i.ExceptionHandlingInterceptor [ExceptionHandlingInterceptor.java:141] Failure during REST processing: ca.uhn.fhir.rest.server.exceptions.InvalidRequestException: Unknown code system: http://fhir.ext.apelon.com/dtsserverws/fhir/ValueSet/2.16.840.1.113883.3.464.1004.1168.8
2018-06-13 08:59:28.002 [http-nio-8080-exec-8] INFO  logging.accesslog [LoggingInterceptor.java:155] ERROR - extended-operation-instance - Measure/measure-bcs

```

**Comment by jeffeastman** [comment]
The ValueSet and its CodeSystem (2.16.840.1.113883.6.12) are both in the database

**Comment by jeffeastman** [comment]
Actually it looks more like a search timeout?

```
2018-06-13 08:59:27.872 [search_coord_9] INFO  c.u.f.j.t.BaseHapiTerminologySvcImpl [BaseHapiTerminologySvcImpl.java:304] Starting expansion around code system: http://fhir.ext.apelon.com/dtsserverws/fhir/ValueSet/2.16.840.1.113883.3.464.1004.1168.8
2018-06-13 08:59:27.872 [http-nio-8080-exec-8] INFO  c.u.f.j.s.SearchCoordinatorSvcImpl [SearchCoordinatorSvcImpl.java:638] Waiting, as we only have 0 results
2018-06-13 08:59:27.874 [http-nio-8080-exec-8] INFO  c.u.f.j.s.SearchCoordinatorSvcImpl [SearchCoordinatorSvcImpl.java:638] Waiting, as we only have 0 results
2018-06-13 08:59:27.876 [http-nio-8080-exec-8] INFO  c.u.f.j.s.SearchCoordinatorSvcImpl [SearchCoordinatorSvcImpl.java:638] Waiting, as we only have 0 results
2018-06-13 08:59:27.877 [http-nio-8080-exec-8] INFO  c.u.f.j.s.SearchCoordinatorSvcImpl [SearchCoordinatorSvcImpl.java:638] Waiting, as we only have 0 results
2018-06-13 08:59:27.879 [http-nio-8080-exec-8] INFO  c.u.f.j.s.SearchCoordinatorSvcImpl [SearchCoordinatorSvcImpl.java:638] Waiting, as we only have 0 results
2018-06-13 08:59:27.880 [http-nio-8080-exec-8] INFO  c.u.f.j.s.SearchCoordinatorSvcImpl [SearchCoordinatorSvcImpl.java:638] Waiting, as we only have 0 results
2018-06-13 08:59:27.882 [http-nio-8080-exec-8] INFO  c.u.f.j.s.SearchCoordinatorSvcImpl [SearchCoordinatorSvcImpl.java:638] Waiting, as we only have 0 results
2018-06-13 08:59:27.883 [http-nio-8080-exec-8] INFO  c.u.f.j.s.SearchCoordinatorSvcImpl [SearchCoordinatorSvcImpl.java:638] Waiting, as we only have 0 results
2018-06-13 08:59:27.885 [http-nio-8080-exec-8] INFO  c.u.f.j.s.SearchCoordinatorSvcImpl [SearchCoordinatorSvcImpl.java:638] Waiting, as we only have 0 results
2018-06-13 08:59:27.887 [http-nio-8080-exec-8] INFO  c.u.f.j.s.SearchCoordinatorSvcImpl [SearchCoordinatorSvcImpl.java:638] Waiting, as we only have 0 results
2018-06-13 08:59:27.888 [http-nio-8080-exec-8] INFO  c.u.f.j.s.SearchCoordinatorSvcImpl [SearchCoordinatorSvcImpl.java:638] Waiting, as we only have 0 results
2018-06-13 08:59:27.890 [http-nio-8080-exec-8] INFO  c.u.f.j.s.SearchCoordinatorSvcImpl [SearchCoordinatorSvcImpl.java:638] Waiting, as we only have 0 results
2018-06-13 08:59:27.892 [http-nio-8080-exec-8] INFO  c.u.f.j.s.SearchCoordinatorSvcImpl [SearchCoordinatorSvcImpl.java:638] Waiting, as we only have 0 results
2018-06-13 08:59:27.894 [http-nio-8080-exec-8] INFO  c.u.f.j.s.SearchCoordinatorSvcImpl [SearchCoordinatorSvcImpl.java:638] Waiting, as we only have 0 results
2018-06-13 08:59:27.895 [http-nio-8080-exec-8] INFO  c.u.f.j.s.SearchCoordinatorSvcImpl [SearchCoordinatorSvcImpl.java:638] Waiting, as we only have 0 results
2018-06-13 08:59:27.897 [http-nio-8080-exec-8] INFO  c.u.f.j.s.SearchCoordinatorSvcImpl [SearchCoordinatorSvcImpl.java:638] Waiting, as we only have 0 results
2018-06-13 08:59:27.899 [http-nio-8080-exec-8] INFO  c.u.f.j.s.SearchCoordinatorSvcImpl [SearchCoordinatorSvcImpl.java:638] Waiting, as we only have 0 results
2018-06-13 08:59:27.900 [http-nio-8080-exec-8] INFO  c.u.f.j.s.SearchCoordinatorSvcImpl [SearchCoordinatorSvcImpl.java:638] Waiting, as we only have 0 results
2018-06-13 08:59:27.902 [http-nio-8080-exec-8] INFO  c.u.f.j.s.SearchCoordinatorSvcImpl [SearchCoordinatorSvcImpl.java:638] Waiting, as we only have 0 results
2018-06-13 08:59:27.904 [http-nio-8080-exec-8] INFO  c.u.f.j.s.SearchCoordinatorSvcImpl [SearchCoordinatorSvcImpl.java:638] Waiting, as we only have 0 results
2018-06-13 08:59:27.905 [http-nio-8080-exec-8] INFO  c.u.f.j.s.SearchCoordinatorSvcImpl [SearchCoordinatorSvcImpl.java:638] Waiting, as we only have 0 results
2018-06-13 08:59:27.907 [http-nio-8080-exec-8] INFO  c.u.f.j.s.SearchCoordinatorSvcImpl [SearchCoordinatorSvcImpl.java:638] Waiting, as we only have 0 results
2018-06-13 08:59:27.908 [http-nio-8080-exec-8] INFO  c.u.f.j.s.SearchCoordinatorSvcImpl [SearchCoordinatorSvcImpl.java:638] Waiting, as we only have 0 results
2018-06-13 08:59:27.934 [http-nio-8080-exec-8] INFO  c.u.f.j.s.SearchCoordinatorSvcImpl [SearchCoordinatorSvcImpl.java:638] Waiting, as we only have 0 results
2018-06-13 08:59:27.936 [http-nio-8080-exec-8] INFO  c.u.f.j.s.SearchCoordinatorSvcImpl [SearchCoordinatorSvcImpl.java:638] Waiting, as we only have 0 results
2018-06-13 08:59:27.937 [http-nio-8080-exec-8] INFO  c.u.f.j.s.SearchCoordinatorSvcImpl [SearchCoordinatorSvcImpl.java:638] Waiting, as we only have 0 results
2018-06-13 08:59:27.939 [http-nio-8080-exec-8] INFO  c.u.f.j.s.SearchCoordinatorSvcImpl [SearchCoordinatorSvcImpl.java:638] Waiting, as we only have 0 results
2018-06-13 08:59:27.941 [http-nio-8080-exec-8] INFO  c.u.f.j.s.SearchCoordinatorSvcImpl [SearchCoordinatorSvcImpl.java:638] Waiting, as we only have 0 results
2018-06-13 08:59:27.943 [http-nio-8080-exec-8] INFO  c.u.f.j.s.SearchCoordinatorSvcImpl [SearchCoordinatorSvcImpl.java:638] Waiting, as we only have 0 results
2018-06-13 08:59:27.945 [http-nio-8080-exec-8] INFO  c.u.f.j.s.SearchCoordinatorSvcImpl [SearchCoordinatorSvcImpl.java:638] Waiting, as we only have 0 results
2018-06-13 08:59:27.946 [http-nio-8080-exec-8] INFO  c.u.f.j.s.SearchCoordinatorSvcImpl [SearchCoordinatorSvcImpl.java:638] Waiting, as we only have 0 results
2018-06-13 08:59:27.948 [http-nio-8080-exec-8] INFO  c.u.f.j.s.SearchCoordinatorSvcImpl [SearchCoordinatorSvcImpl.java:638] Waiting, as we only have 0 results
2018-06-13 08:59:27.949 [http-nio-8080-exec-8] INFO  c.u.f.j.s.SearchCoordinatorSvcImpl [SearchCoordinatorSvcImpl.java:638] Waiting, as we only have 0 results
2018-06-13 08:59:27.951 [http-nio-8080-exec-8] INFO  c.u.f.j.s.SearchCoordinatorSvcImpl [SearchCoordinatorSvcImpl.java:638] Waiting, as we only have 0 results
2018-06-13 08:59:27.953 [http-nio-8080-exec-8] INFO  c.u.f.j.s.SearchCoordinatorSvcImpl [SearchCoordinatorSvcImpl.java:638] Waiting, as we only have 0 results
2018-06-13 08:59:27.954 [http-nio-8080-exec-8] INFO  c.u.f.j.s.SearchCoordinatorSvcImpl [SearchCoordinatorSvcImpl.java:638] Waiting, as we only have 0 results
2018-06-13 08:59:27.955 [http-nio-8080-exec-8] INFO  c.u.f.j.s.SearchCoordinatorSvcImpl [SearchCoordinatorSvcImpl.java:638] Waiting, as we only have 0 results
2018-06-13 08:59:27.957 [http-nio-8080-exec-8] INFO  c.u.f.j.s.SearchCoordinatorSvcImpl [SearchCoordinatorSvcImpl.java:638] Waiting, as we only have 0 results
2018-06-13 08:59:27.959 [http-nio-8080-exec-8] INFO  c.u.f.j.s.SearchCoordinatorSvcImpl [SearchCoordinatorSvcImpl.java:638] Waiting, as we only have 0 results
2018-06-13 08:59:27.962 [http-nio-8080-exec-8] INFO  c.u.f.j.s.SearchCoordinatorSvcImpl [SearchCoordinatorSvcImpl.java:638] Waiting, as we only have 0 results
2018-06-13 08:59:27.964 [http-nio-8080-exec-8] INFO  c.u.f.j.s.SearchCoordinatorSvcImpl [SearchCoordinatorSvcImpl.java:638] Waiting, as we only have 0 results
2018-06-13 08:59:27.965 [http-nio-8080-exec-8] INFO  c.u.f.j.s.SearchCoordinatorSvcImpl [SearchCoordinatorSvcImpl.java:638] Waiting, as we only have 0 results
2018-06-13 08:59:27.967 [http-nio-8080-exec-8] INFO  c.u.f.j.s.SearchCoordinatorSvcImpl [SearchCoordinatorSvcImpl.java:638] Waiting, as we only have 0 results
2018-06-13 08:59:27.969 [http-nio-8080-exec-8] INFO  c.u.f.j.s.SearchCoordinatorSvcImpl [SearchCoordinatorSvcImpl.java:638] Waiting, as we only have 0 results
2018-06-13 08:59:27.970 [http-nio-8080-exec-8] INFO  c.u.f.j.s.SearchCoordinatorSvcImpl [SearchCoordinatorSvcImpl.java:638] Waiting, as we only have 0 results
2018-06-13 08:59:27.971 [http-nio-8080-exec-8] INFO  c.u.f.j.s.SearchCoordinatorSvcImpl [SearchCoordinatorSvcImpl.java:638] Waiting, as we only have 0 results
2018-06-13 08:59:27.973 [http-nio-8080-exec-8] INFO  c.u.f.j.s.SearchCoordinatorSvcImpl [SearchCoordinatorSvcImpl.java:638] Waiting, as we only have 0 results
2018-06-13 08:59:27.974 [http-nio-8080-exec-8] INFO  c.u.f.j.s.SearchCoordinatorSvcImpl [SearchCoordinatorSvcImpl.java:638] Waiting, as we only have 0 results
2018-06-13 08:59:27.976 [http-nio-8080-exec-8] INFO  c.u.f.j.s.SearchCoordinatorSvcImpl [SearchCoordinatorSvcImpl.java:638] Waiting, as we only have 0 results
2018-06-13 08:59:27.978 [http-nio-8080-exec-8] INFO  c.u.f.j.s.SearchCoordinatorSvcImpl [SearchCoordinatorSvcImpl.java:638] Waiting, as we only have 0 results
2018-06-13 08:59:27.979 [http-nio-8080-exec-8] INFO  c.u.f.j.s.SearchCoordinatorSvcImpl [SearchCoordinatorSvcImpl.java:638] Waiting, as we only have 0 results
2018-06-13 08:59:27.981 [http-nio-8080-exec-8] INFO  c.u.f.j.s.SearchCoordinatorSvcImpl [SearchCoordinatorSvcImpl.java:638] Waiting, as we only have 0 results
2018-06-13 08:59:27.983 [http-nio-8080-exec-8] INFO  c.u.f.j.s.SearchCoordinatorSvcImpl [SearchCoordinatorSvcImpl.java:638] Waiting, as we only have 0 results
2018-06-13 08:59:27.984 [http-nio-8080-exec-8] INFO  c.u.f.j.s.SearchCoordinatorSvcImpl [SearchCoordinatorSvcImpl.java:638] Waiting, as we only have 0 results
2018-06-13 08:59:27.986 [http-nio-8080-exec-8] INFO  c.u.f.j.s.SearchCoordinatorSvcImpl [SearchCoordinatorSvcImpl.java:638] Waiting, as we only have 0 results
2018-06-13 08:59:27.987 [http-nio-8080-exec-8] INFO  c.u.f.j.s.SearchCoordinatorSvcImpl [SearchCoordinatorSvcImpl.java:638] Waiting, as we only have 0 results
2018-06-13 08:59:27.989 [http-nio-8080-exec-8] INFO  c.u.f.j.s.SearchCoordinatorSvcImpl [SearchCoordinatorSvcImpl.java:638] Waiting, as we only have 0 results
2018-06-13 08:59:27.990 [http-nio-8080-exec-8] INFO  c.u.f.j.s.SearchCoordinatorSvcImpl [SearchCoordinatorSvcImpl.java:638] Waiting, as we only have 0 results
2018-06-13 08:59:27.991 [http-nio-8080-exec-8] INFO  c.u.f.j.s.SearchCoordinatorSvcImpl [SearchCoordinatorSvcImpl.java:638] Waiting, as we only have 0 results
2018-06-13 08:59:27.993 [http-nio-8080-exec-8] INFO  c.u.f.j.s.SearchCoordinatorSvcImpl [SearchCoordinatorSvcImpl.java:638] Waiting, as we only have 0 results
2018-06-13 08:59:27.995 [http-nio-8080-exec-8] INFO  c.u.f.j.s.SearchCoordinatorSvcImpl [SearchCoordinatorSvcImpl.java:638] Waiting, as we only have 0 results
2018-06-13 08:59:27.996 [http-nio-8080-exec-8] INFO  c.u.f.j.s.SearchCoordinatorSvcImpl [SearchCoordinatorSvcImpl.java:638] Waiting, as we only have 0 results
2018-06-13 08:59:27.998 [http-nio-8080-exec-8] INFO  c.u.f.j.s.SearchCoordinatorSvcImpl [SearchCoordinatorSvcImpl.java:638] Waiting, as we only have 0 results
2018-06-13 08:59:27.999 [http-nio-8080-exec-8] INFO  c.u.f.j.s.SearchCoordinatorSvcImpl [SearchCoordinatorSvcImpl.java:638] Waiting, as we only have 0 results
2018-06-13 08:59:28.001 [search_coord_9] WARN  c.u.f.j.s.SearchCoordinatorSvcImpl [SearchCoordinatorSvcImpl.java:537] Failed during search due to invalid request: ca.uhn.fhir.rest.server.exceptions.InvalidRequestException: Unknown code system: http://fhir.ext.apelon.com/dtsserverws/fhir/ValueSet/2.16.840.1.113883.3.464.1004.1168.8
2018-06-13 08:59:28.001 [http-nio-8080-exec-8] INFO  c.u.f.j.s.SearchCoordinatorSvcImpl [SearchCoordinatorSvcImpl.java:647] Proceeding, as we have 0 results
2018-06-13 08:59:28.001 [http-nio-8080-exec-8] WARN  c.u.f.r.s.i.ExceptionHandlingInterceptor [ExceptionHandlingInterceptor.java:141] Failure during REST processing: ca.uhn.fhir.rest.server.exceptions.InvalidRequestException: Unknown code system: http://fhir.ext.apelon.com/dtsserverws/fhir/ValueSet/2.16.840.1.113883.3.464.1004.1168.8
2018-06-13 08:59:28.002 [http-nio-8080-exec-8] INFO  logging.accesslog [LoggingInterceptor.java:155] ERROR - extended-operation-instance - Measure/measure-bcs
2018-06-13 09:03:30.905 [http-nio-8080-exec-7] INFO  logging.accesslog [LoggingInterceptor.java:170] Source[127.0.0.1] Operation[metadata ] UA[HAPI-FHIR/3.4.0 (FHIR Client; FHIR 3.0.1/DSTU3; apache)] Params[?_pretty=true]

```

**Comment by c-schuler** [comment]
I see. Looks like you're using a remote terminology provider instead of the Ruler. I have updated the terminology provider in the Ruler to use HAPI's terminology service. It appears that there is an issue when using that with a remote terminology service. Would you mind PMing me the authorization info so I can test that service?

**Comment by jeffeastman** [comment]
This one is running on my machine, and it has all of the CodeSystems and ValueSets loaded, so it should be its own terminology provider.

**Comment by c-schuler** [comment]
Why then is it saying:
`Unknown code system: http://fhir.ext.apelon.com/dtsserverws/fhir/ValueSet/2.16.840.1.113883.3.464.1004.1168.8`
instead of something like:
`Unknown code system: http://localhost:8080/cqf-ruler/baseDstu3/ValueSet/2.16.840.1.113883.3.464.1004.1168.8`
? 
Am I missing something?

**Comment by jeffeastman** [comment]
Good point, but the CodeSystems and ValueSets are loaded on my local server. I’ve provisioned it exactly the same as I’ve been doing for months.

**Comment by jeffeastman** [comment]
Looks like a lot has changed in the JpaTerminologyProvider since the last commit.

**Comment by c-schuler** [comment]
@jeffeastman is this still an issue?
