### ISSUE TITLE
String null exception

### ISSUE THREAD

**Issue by rob-reynolds** [DBCG/cqf-ruler#581]
IS: 
ca.uhn.fhir.rest.server.exceptions.InternalErrorException: Failed to call access method: java.lang.NullPointerException: Cannot invoke "String.length()" because "str" is null

        at org.opencds.cqf.cql.evaluator.measure.r4.R4MeasureReportBuilder.createResourceReferenceValue(R4MeasureReportBuilder.java:484)
        at org.opencds.cqf.cql.evaluator.measure.r4.R4MeasureReportBuilder.processSdeEvaluatedResourceExtension(R4MeasureReportBuilder.java:455)
        at org.opencds.cqf.cql.evaluator.measure.r4.R4MeasureReportBuilder.processSdes(R4MeasureReportBuilder.java:347)
        at org.opencds.cqf.cql.evaluator.measure.r4.R4MeasureReportBuilder.build(R4MeasureReportBuilder.java:91)
        
        
 SHOULD BE: no error
 
 
 REPRO:
 clone the Risk Adjustment repository: https://github.com/HL7/davinci-ra.git
 switch to the sde-tests branch
 in ThunderClient extension, Env tab, configure RAServer to your CQF Ruler instance
 In ThunderClient extension, Collections tab, run the $risk-adjustment Operation, Config requests
 run the Evaluate HCC189 - Historic - Closed request

**Comment by rob-reynolds** [comment]
Can't repro with latest.
