### ISSUE TITLE
$evaluate need the library.name == library.id

### ISSUE THREAD

**Issue by delcroip** [DBCG/cqf-ruler#602]

**Comment by delcroip** [comment]
Dear,

I tried for some time to evaluate libraries  but it seems it only works when library.name == library.id else I am getting this error : Unable translate library

here tge error on the log 
```
eEncoding[JSON] Operation[update  Library/emcaredt01] UA[vscode-restclient] Params[] ResponseEncoding[JSON]
cqf-ruler           | 2022-09-16 09:32:53.690 [http-nio-8080-exec-5] INFO  ca.uhn.fhir.context.FhirContext [FhirContext.java:206] Creating new FHIR context for FHIR version [DSTU3]
cqf-ruler           | org.opencds.cqf.cql.engine.exception.CqlException: Unable translate library emcaredt01
cqf-ruler           | 	at org.opencds.cqf.cql.evaluator.engine.execution.TranslatingLibraryLoader.translate(TranslatingLibraryLoader.java:128)
cqf-ruler           | 	at org.opencds.cqf.cql.evaluator.engine.execution.TranslatingLibraryLoader.load(TranslatingLibraryLoader.java:78)
cqf-ruler           | 	at org.opencds.cqf.cql.evaluator.engine.execution.CacheAwareLibraryLoaderDecorator.load(CacheAwareLibraryLoaderDecorator.java:49)
cqf-ruler           | 	at org.opencds.cqf.cql.engine.execution.CqlEngine.loadAndValidate(CqlEngine.java:251)
cqf-ruler           | 	at org.opencds.cqf.cql.engine.execution.CqlEngine.evaluate(CqlEngine.java:154)
cqf-ruler           | 	at org.opencds.cqf.cql.evaluator.CqlEvaluator.evaluate(CqlEvaluator.java:89)
cqf-ruler           | 	at org.opencds.cqf.cql.evaluator.library.LibraryEvaluator.evaluate(LibraryEvaluator.java:47)
cqf-ruler           | 	at org.opencds.cqf.ruler.cpg.r4.provider.LibraryEvaluationProvider.evaluate(LibraryEvaluationProvider.java:170)
cqf-ruler           | 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
cqf-ruler           | 	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
cqf-ruler           | 	at ca.uhn.fhir.rest.server.method.BaseMethodBinding.invokeServerMethod(BaseMethodBinding.java:264)
cqf-ruler           | 	at ca.uhn.fhir.rest.server.method.OperationMethodBinding.invokeServer(OperationMethodBinding.java:332)
cqf-ruler           | 	at ca.uhn.fhir.rest.server.method.BaseResourceReturningMethodBinding.doInvokeServer(BaseResourceReturningMethodBinding.java:326)
cqf-ruler           | 	at ca.uhn.fhir.rest.server.method.BaseResourceReturningMethodBinding.invokeServer(BaseResourceReturningMethodBinding.java:434)
cqf-ruler           | 	at ca.uhn.fhir.rest.server.method.OperationMethodBinding.invokeServer(OperationMethodBinding.java:307)
cqf-ruler           | 	at ca.uhn.fhir.rest.server.RestfulServer.handleRequest(RestfulServer.java:1152)
cqf-ruler           | 	at ca.uhn.fhir.rest.server.RestfulServer.doPost(RestfulServer.java:423)
cqf-ruler           | 	at ca.uhn.fhir.rest.server.RestfulServer.service(RestfulServer.java:1861)
cqf-ruler           | 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:764)
cqf-ruler           | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227)
cqf-ruler           | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
cqf-ruler           | 	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
cqf-ruler           | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
cqf-ruler           | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
cqf-ruler           | 	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
cqf-ruler           | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
cqf-ruler           | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
cqf-ruler           | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
cqf-ruler           | 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:197)
cqf-ruler           | 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
cqf-ruler           | 	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
cqf-ruler           | 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135)
cqf-ruler           | 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
cqf-ruler           | 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
cqf-ruler           | 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:360)
cqf-ruler           | 	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:399)
cqf-ruler           | 	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
cqf-ruler           | 	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:889)
cqf-ruler           | 	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1743)
cqf-ruler           | 	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
cqf-ruler           | 	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
cqf-ruler           | 	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
cqf-ruler           | 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
cqf-ruler           | 	at java.base/java.lang.Thread.run(Thread.java:833)
cqf-ruler           | Caused by: java.lang.IllegalArgumentException: Could not load source for library emcaredt01, version 4.0.1.
cqf-ruler           | 	at org.cqframework.cql.cql2elm.PriorityLibrarySourceLoader.getLibrarySource(PriorityLibrarySourceLoader.java:72)
cqf-ruler           | 	at org.cqframework.cql.cql2elm.LibraryManager.translateLibrary(LibraryManager.java:208)
cqf-ruler           | 	at org.cqframework.cql.cql2elm.LibraryManager.resolveLibrary(LibraryManager.java:184)
cqf-ruler           | 	at org.opencds.cqf.cql.evaluator.engine.execution.TranslatingLibraryLoader.translate(TranslatingLibraryLoader.java:125)
cqf-ruler           | 	... 43 more
cqf-ruler           | 2022-09-16 09:32:53.716 [http-nio-8080-exec-5] INFO  fhirtest.access [LoggingInterceptor.java:175] Path[/fhir] Source[51.154.169.129] Operation[extended-operation-instance $evaluate Library/emcaredt01] UA[vscode-restclient] Params[?subject=%2FPatient%2Fpatient0] ResponseEncoding[] Operation[extended-operation-instance $evaluate Library/emcaredt01] UA[vscode-restclient] Params[?subject=%2FPatient%2Fpatient0] ResponseEncoding[]

```

**Comment by JPercival** [comment]
Hi @delcroip!

Thanks for the report. I took a look at the relevant code that requires the CQL library name match the FHIR library name, and it looks right to me. Do you have to have a repro of this issue you can share?

**Comment by delcroip** [comment]
Here is the post that create the issue if the name doesn't match the id

```
POST https://fhir.ruler.dk.swisstph-mis.ch/fhir/Library/emcaredt01/$evaluate?subject=/Patient/patient0
```

here is a copy of the resource:


[library-emcaredt01.json.zip](https://github.com/DBCG/cqf-ruler/files/9610669/library-emcaredt01.json.zip)

if you remove the dot(.) in the name it will work

br

**Comment by c-schuler** [comment]
@delcroip it isn't that the Library.name element needs to be the same as the Library.id. The issue is that the library.name needs to be the same as the CQL library name declaration. Please refer to the following documentation: http://hl7.org/fhir/uv/cpg/libraries.html#library-name-and-url
Looking at the CQL attached to the Library resource you shared, it has `library emcaredt01 version '4.0.1'`. Therefore, the Library.name should be `emcaredt01 `
Does that make sense?

**Comment by delcroip** [comment]
It does, thank you.

 i took the assumption that the lib name in cql should be equal to the id and not the name.

To be on the safe side, I will run other test to check if having the cql lib name != Id works

**Comment by delcroip** [comment]
Is there something to do to allow dot (.) In a library name, i read that it creates a domain but not how to make it work (i was getting an error, i will also get more details unless i missed again something)

**Comment by c-schuler** [comment]
Is this what you're looking for? http://hl7.org/fhir/uv/cpg/libraries.html#library-namespaces

**Comment by delcroip** [comment]
I will send more details but when i tried emcare.dt01 as a name in the CQL lib i got an error when generating the elm.

**Comment by delcroip** [comment]
I double check and it works as described, the dot issue just confused me and I started changing the id, names ....  Should I create another issue for the point above or I missed something (again)

thanks you for your support

**Comment by c-schuler** [comment]
@delcroip The namespace needs to be registered with the translator. I am not sure how you are running the CQL, but here are some examples on how to register namespaces using the [NamespaceManager](https://github.com/cqframework/clinical_quality_language/blob/master/Src/java/model/src/main/java/org/hl7/cql/model/NamespaceManager.java):

- https://github.com/cqframework/clinical_quality_language/blob/master/Src/java/cql-to-elm/src/main/java/org/cqframework/cql/cql2elm/CqlCompiler.java
- https://github.com/cqframework/clinical_quality_language/blob/master/Src/java/cql-to-elm/src/main/java/org/cqframework/cql/cql2elm/CqlTranslator.java
- https://github.com/cqframework/clinical_quality_language/blob/master/Src/java/cql-to-elm/src/main/java/org/cqframework/cql/cql2elm/ModelManager.java
