### ISSUE TITLE
Tomcat Startup Error

### ISSUE THREAD

**Issue by jeffeastman** [DBCG/cqf-ruler#76]
```
2018-10-17 11:47:20.952 [localhost-startStop-1] INFO  o.s.w.c.s.AnnotationConfigWebApplicationContext [AbstractApplicationContext.java:590] Refreshing WebApplicationContext for namespace 'spring-servlet': startup date [Wed Oct 17 11:47:20 EDT 2018]; parent: Root WebApplicationContext
2018-10-17 11:47:20.955 [localhost-startStop-1] INFO  o.s.w.c.s.AnnotationConfigWebApplicationContext [AnnotationConfigWebApplicationContext.java:233] Successfully resolved class for [org.opencds.cqf.config.BaseFhirTesterConfig]
2018-10-17 11:47:21.155 [localhost-startStop-1] WARN  o.s.w.c.s.AnnotationConfigWebApplicationContext [AbstractApplicationContext.java:558] Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'controller': Unsatisfied dependency expressed through field 'myConfig'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'testerConfig' defined in org.opencds.cqf.config.BaseFhirTesterConfig: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [ca.uhn.fhir.to.TesterConfig]: Factory method 'testerConfig' threw exception; nested exception is java.lang.NullPointerException: theBaseUrl can not be blank
2018-10-17 11:47:21.157 [localhost-startStop-1] ERROR o.s.web.servlet.DispatcherServlet [FrameworkServlet.java:503] Context initialization failed
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'controller': Unsatisfied dependency expressed through field 'myConfig'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'testerConfig' defined in org.opencds.cqf.config.BaseFhirTesterConfig: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [ca.uhn.fhir.to.TesterConfig]: Factory method 'testerConfig' threw exception; nested exception is java.lang.NullPointerException: theBaseUrl can not be blank
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:587)
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:91)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:373)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1344)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:582)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:502)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:312)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:228)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:310)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:761)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:869)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:550)
	at org.springframework.web.servlet.FrameworkServlet.configureAndRefreshWebApplicationContext(FrameworkServlet.java:672)
	at org.springframework.web.servlet.FrameworkServlet.createWebApplicationContext(FrameworkServlet.java:638)
	at org.springframework.web.servlet.FrameworkServlet.createWebApplicationContext(FrameworkServlet.java:686)
	at org.springframework.web.servlet.FrameworkServlet.initWebApplicationContext(FrameworkServlet.java:554)
	at org.springframework.web.servlet.FrameworkServlet.initServletBean(FrameworkServlet.java:499)
	at org.springframework.web.servlet.HttpServletBean.init(HttpServletBean.java:172)
	at javax.servlet.GenericServlet.init(GenericServlet.java:158)
	at org.apache.catalina.core.StandardWrapper.initServlet(StandardWrapper.java:1183)
	at org.apache.catalina.core.StandardWrapper.loadServlet(StandardWrapper.java:1099)
	at org.apache.catalina.core.StandardWrapper.load(StandardWrapper.java:989)
	at org.apache.catalina.core.StandardContext.loadOnStartup(StandardContext.java:4931)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5241)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:752)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:728)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:734)
	at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:986)
	at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1857)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'testerConfig' defined in org.opencds.cqf.config.BaseFhirTesterConfig: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [ca.uhn.fhir.to.TesterConfig]: Factory method 'testerConfig' threw exception; nested exception is java.lang.NullPointerException: theBaseUrl can not be blank
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:587)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1250)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1099)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:545)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:502)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:312)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:228)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:310)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200)
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:251)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1138)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1065)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:584)
	... 35 common frames omitted
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [ca.uhn.fhir.to.TesterConfig]: Factory method 'testerConfig' threw exception; nested exception is java.lang.NullPointerException: theBaseUrl can not be blank
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:579)
	... 47 common frames omitted
Caused by: java.lang.NullPointerException: theBaseUrl can not be blank
	at org.apache.commons.lang3.Validate.notBlank(Validate.java:451)
	at ca.uhn.fhir.to.TesterConfig$ServerBuilder.withBaseUrl(TesterConfig.java:175)
	at org.opencds.cqf.config.BaseFhirTesterConfig.testerConfig(BaseFhirTesterConfig.java:23)
	at org.opencds.cqf.config.BaseFhirTesterConfig$$EnhancerBySpringCGLIB$$184c9850.CGLIB$testerConfig$0(<generated>)
	at org.opencds.cqf.config.BaseFhirTesterConfig$$EnhancerBySpringCGLIB$$184c9850$$FastClassBySpringCGLIB$$261a106.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228)
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:361)
	at org.opencds.cqf.config.BaseFhirTesterConfig$$EnhancerBySpringCGLIB$$184c9850.testerConfig(<generated>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154)
	... 48 common frames omitted
2018-10-17 11:47:21.165 [localhost-startStop-1] INFO  o.s.w.c.s.AnnotationConfigWebApplicationContext [AbstractApplicationContext.java:590] Refreshing Root WebApplicationContext: startup date [Wed Oct 17 11:47:21 EDT 2018]; parent: Root WebApplicationContext
2018-10-17 11:47:21.167 [localhost-startStop-1] INFO  o.s.w.c.s.AnnotationConfigWebApplicationContext [AnnotationConfigWebApplicationContext.java:213] Registering annotated classes: [class org.opencds.cqf.config.FhirServerConfigDstu3,class ca.uhn.fhir.jpa.config.WebsocketDispatcherConfig]
2018-10-17 11:47:21.744 [localhost-startStop-1] INFO  o.s.o.j.LocalContainerEntityManagerFactoryBean [LocalContainerEntityManagerFactoryBean.java:361] Building JPA container EntityManagerFactory for persistence unit 'PU_HapiFhirJpaDstu3'
2018-10-17 11:47:21.744 [localhost-startStop-1] INFO  o.h.jpa.internal.util.LogHelper [LogHelper.java:31] HHH000204: Processing PersistenceUnitInfo [
	name: PU_HapiFhirJpaDstu3
	...]

```

**Comment by c-schuler** [comment]
I believe this is happening because the following [Maven property](https://github.com/DBCG/cqf-ruler/blob/master/pom.xml#L21) needs to be set when starting Tomcat. I will test this shortly and provide documentation. Thanks @jeffeastman!

**Comment by c-schuler** [comment]
Hey @jeffeastman:

I was able to figure this out. You'll need to create a file called setenv.sh in the {TOMCAT_HOME}/bin directory. Here is an example of the content:

```
CATALINA_OPTS="${CATALINA_OPTS} -DprotocolAndHost=http://localhost:8080 -Ddstu3Path=cqf-ruler/baseDstu3 -Ddstu2Path=cqf-ruler/baseDstu2 -Dr4Path=cqf-ruler/baseR4 -Ddev=true -Dfhir.baseurl.r4=http://localhost:8080/cqf-ruler/baseR4 -Dfhir.baseurl.dstu3=http://localhost:8080/cqf-ruler/baseDstu3 -Dfhir.baseurl.dstu2=http://localhost:8080/cqf-ruler/baseDstu2"
```

Edit that as necessary. Let me know if this solves the problem. I tested this on my Mac (using Mojave) using Tomcat v9.0.1

**Comment by c-schuler** [comment]
@jeffeastman I believe this issue has been resolved for you, right?
Closing. Feel free to reopen if the problem persists.
